### ISSUE TITLE
No way to update session expiration

### ISSUE THREAD

**Issue by vostrnad** [fastify/fastify-secure-session#225]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I got a little confused by this code snippet in the README:

```js
fastify.get('/ping', (request, reply) => {
  request.session.options({maxAge: 3600})
  
  // Send the session cookie to the client even if the session data didn't change
  // can be used to update cookie expiration
  request.session.touch()
  reply.send('pong')
})
```

It turns out this does *not* change when the session expires, it only changes what `Max-Age` is sent to the browser. I looked around and didn't find a way to actually extend a session. Is this intentional, or is it a missing feature that could be added?

**Comment by mcollina** [comment]
This is by design. You can increase the expiry in the plugin config.
Otherwise a leaked session cookie could persist forever.

**Comment by andreialecu** [comment]
@mcollina I'm concerned about this change.

This behavior was introduced in [version 7.3.0](https://github.com/fastify/fastify-secure-session/commit/56d66642ecc633cff0606927601e81cdac361370) as a non-major update, despite significantly impacting session behavior. This feels like a breaking change that ideally should've been reserved for a major release.

Key issues:

The default session expiry is now fixed at just 1 day, limiting the ability for users to remain logged in beyond this period.

In SPAs, this leads to unpredictable behavior. For example, if a user logs in at 23h 59min, API requests will suddenly fail 1 minute later, causing confusion and potential disruption.

We experienced substantial problems with our application due to this update. It makes me question whether the library is being adequately dogfooded in real-world scenarios to prevent such critical issues from arising.

I think a better solution would've been to include the session expiry as part of the cookie, and allow updating it. This would prevent cookies from being reused, but still allow updating their expiration.

**Comment by mcollina** [comment]
It was done as a minor because it was a security change.

**Comment by andreialecu** [comment]
Please read my message again. It is a huge breaking change, and the way the security change was implemented is deeply flawed for the reasons mentioned above.

Even if it's a security change, it completely breaks any nontrivial apps.

There should be a way to update the session expiration in the cookie. If the timestamp is in the cookie and can be updated, there's no way to reuse that cookie past its expiration.

> Otherwise a leaked session cookie could persist forever.

How could this happen?

**Comment by andreialecu** [comment]
Essentially there is no way at the moment to do anything to a cookie to extend it past its initial 1 day from when it was first created.
